# Generated by Django 3.1.7 on 2021-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
        ),
    ]
