# Generated by Django 3.1.7 on 2021-04-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchimages', '0002_geolocations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoLocations',
            new_name='GeoLocationList',
        ),
    ]
